alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
ingress:
  rules:
  - component:
      name: nuxt-toot
    match:
      path:
        prefix: /
name: nuxt-toot
region: nyc
services:
- build_command: npm run build
  run_command: npm run start
  environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: tompscanlan/nuxt-toot
  http_port: 8080
  instance_count: 1
  instance_size_slug: professional-xs
  name: nuxt-toot
  source_dir: /
